apiVersion: v1
kind: Pod
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  containers:
  - name: postgres
    image: postgres:16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_DB
        value: auth_db
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
