apiVersion: v1
kind: Pod
metadata: 
  name: auth-service
  labels: 
    app: auth-service
spec:
  containers:
  - name: auth-service
    image: auth-service:4.0
    ports:
      - containerPort: 8080
    env:
    
      - name: SPRING_PROFILES_ACTIVE
        value: docker

      - name: DB_URL
        value: jdbc:postgresql://postgres:5432/auth_db

      - name: POSTGRES_URL
        value: jdbc:postgresql://postgres:5432/auth_db

      - name: DB_USER
        value: postgres

      - name: DB_PASSWORD
        value: postgres

      - name: REDIS_HOST
        value: redis

      - name: REDIS_PORT
        value: "6379"

      - name: JWT_SECRET
        value: HUDghelsbojnxUIÇFWnvvnkvbizklnÇBIvçiahiyagbvhudsoIUHVBOOAOHVkgvualojvnknshblvayoaukelivboayluvoavbhjaulvlupanbihbuçhp94uphUHIÇFçnibozj90238uy7pUVhpwep9ihçbzpiNUÇHBOephifnçovin3iijph3y8oqjvnmcnbvahlbvhlaiçoijhp8yuir