spring:
  profile: docker
  datasource:
    url: ${POSTGRES_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver_class_name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 1500000
  refresh-expiration: 604800000