spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    DRIVER_CLASS_NAME: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000